const KEY='betonTG.formulas.v1';
const DEFAULT=[{name:'B30',materials:{G1:{kg:543,d:1450},G2:{kg:534,d:1450},SL:{kg:427,d:1600},SC:{kg:427,d:1450},Ciment:{kg:320,d:null},Adjuvant:{kg:3.4,d:null},Eau:{kg:158,d:null}}},{name:'B35',materials:{G1:{kg:543,d:1450},G2:{kg:530,d:1450},SL:{kg:418,d:1600},SC:{kg:417,d:1450},Ciment:{kg:350,d:null},Adjuvant:{kg:3.8,d:null},Eau:{kg:156,d:null}}}];
let formulas=JSON.parse(localStorage.getItem(KEY)||JSON.stringify(DEFAULT));const $=id=>document.getElementById(id);const volumeM=new Set(['G1','G2','SL','SC']);
function save(){localStorage.setItem(KEY,JSON.stringify(formulas))}function kg(x){x=Math.round(x*100)/100;return Number.isInteger(x)?x:x.toFixed(2)}function m3(x){return x.toFixed(2)}
function types(selected){$('type').innerHTML=formulas.map(f=>`<option>${f.name}</option>`).join('');if(selected&&formulas.some(f=>f.name===selected))$('type').value=selected}
function calc(){const f=formulas.find(x=>x.name===$('type').value),q=Number($('qty').value);if(!f||!q||q<0){$('results').innerHTML='<p>Veuillez saisir une quantité supérieure à 0 m³.</p>';return}$('badge').textContent=f.name;$('results').innerHTML='';for(const [name,d] of Object.entries(f.materials)){const mass=d.kg*q;const vol=volumeM.has(name)&&d.d?`→ ${m3(mass/d.d)} m³`:'';$('results').insertAdjacentHTML('beforeend',`<div class="row"><div class="mat">${name}</div><div class="mass">${kg(mass)} kg</div><div class="vol">${vol}</div></div>`)} }
function toast(t){$('toast').textContent=t;$('toast').classList.add('show');clearTimeout(window.tt);window.tt=setTimeout(()=>$('toast').classList.remove('show'),2000)}
function render(){const ed=$('editor');ed.innerHTML='';formulas.forEach((f,i)=>{const card=document.createElement('div');card.className='fcard';card.innerHTML=`<div class="fhead"><b>${f.name}</b><button class="small del">Supprimer</button></div><label>Nom de la formule<input class="fname" value="${f.name}"></label><div class="fgrid"></div>`;const grid=card.querySelector('.fgrid');Object.entries(f.materials).forEach(([n,d])=>{const w=document.createElement('div');w.innerHTML=`<label>${n} — kg/m³<input class="massIn" type="number" min="0" step="0.01" value="${d.kg}"></label>${volumeM.has(n)?`<label>Densité ${n} — kg/m³<input class="denIn" type="number" min="1" step="1" value="${d.d||''}"></label>`:''}`;grid.appendChild(w);w.querySelector('.massIn').onchange=e=>{d.kg=Math.max(0,Number(e.target.value)||0);save();calc();toast('Valeur enregistrée.')};if(volumeM.has(n))w.querySelector('.denIn').onchange=e=>{d.d=Math.max(1,Number(e.target.value)||1);save();calc();toast('Densité enregistrée.')};});card.querySelector('.fname').onchange=e=>{let n=e.target.value.trim().toUpperCase();if(!n||formulas.some((x,j)=>j!==i&&x.name===n)){e.target.value=f.name;toast('Nom invalide ou déjà utilisé.');return}f.name=n;save();types(n);render();calc()};card.querySelector('.del').onclick=()=>{if(formulas.length<2)return toast('Il faut conserver au moins une formule.');if(confirm(`Supprimer ${f.name} ?`)){formulas.splice(i,1);save();types();render();calc();toast('Formule supprimée.')}};ed.appendChild(card)})}
$('calc').onclick=calc;$('qty').oninput=calc;$('type').onchange=calc;$('toggle').onclick=()=>{$('panel').hidden=!$('panel').hidden;if(!$('panel').hidden)render()};$('add').onclick=()=>{let n=25;while(formulas.some(f=>f.name==='B'+n))n+=5;formulas.push({name:'B'+n,materials:{G1:{kg:0,d:1450},G2:{kg:0,d:1450},SL:{kg:0,d:1600},SC:{kg:0,d:1450},Ciment:{kg:0,d:null},Adjuvant:{kg:0,d:null},Eau:{kg:0,d:null}}});save();types('B'+n);render();calc();toast('Formule ajoutée.')};$('reset').onclick=()=>{if(confirm('Réinitialiser les formules V1 ?')){formulas=JSON.parse(JSON.stringify(DEFAULT));save();types('B30');render();calc();toast('Formules restaurées.')}};
let deferred=null;window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferred=e;$('install').hidden=false});$('install').onclick=async()=>{if(deferred){deferred.prompt();await deferred.userChoice;deferred=null;$('install').hidden=true}};
if('serviceWorker' in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('service-worker.js').catch(()=>{}));types('B30');calc();
